# La-MAML specific defaults
model: lamaml_cifar
loader: class_incremental_loader
learn_lr: true
sync_update: false
use_old_task_memory: false
second_order: false

opt_lr: 0.03 # n
alpha_init: 0.01 # alpha
momentum: 0.9
