# La-MAML specific defaults
model: lamaml_cifar
loader: task_incremental_loader
learn_lr: true
sync_update: false
use_old_task_memory: false
second_order: false

opt_lr: 0.1 # n
alpha_init: 0.001 # alpha
momentum: 0.9
